### ISSUE TITLE
Терминология. Двоичные приставки

### ISSUE THREAD

**Issue by lunakoly** [Kotlin-Polytech/KotlinAsFirst2018#1]
В _chapter04_5.adoc_ **1 килобайт** определяется как **2^10 байт**. 
Разве не было бы корректнее определить **1 килобайт** как **1000 байт**, а для обозначения **2^10** байт использовать термин **"кибибайт"**?

**Comment by ice-phoenix** [comment]
С точки зрения МЭК вы, безусловно, правы. Однако даже в нашей с вами области (для которой бинарные приставки-множители и придумали) все еще очень много где термин KB или килобайт используется именно в смысле 2^10 байт. По этой причине мы следуем тому, что является общепринятым в области.

Вместе с тем, упомянуть про кибибайт и его друзей, наверное, следует. Обязательно это исправим в будущем.

**Comment by mglukhikh** [comment]
Преобразовал в тикет базовой репо: https://github.com/Kotlin-Polytech/KotlinAsFirst/issues/59
