### ISSUE TITLE
Ошибка в тестах для функции dateDigitToStr

### ISSUE THREAD

**Issue by nikiforovta** [Kotlin-Polytech/KotlinAsFirst2018#11]
В последних двух тестах для функции dateDigitToStr в 6 уроке "проверяется" предыдущая функция (dateStrToDigit).

**Comment by gagarski** [comment]
Починено в 29859d8dee596d9fbfeec0a06c083e846874f248.
Можете влить изменения из этого репозитория к себе, либо перенести их вручную.
