### ISSUE TITLE
Опечатка в описании функции flattenPhoneNumber

### ISSUE THREAD

**Issue by nikiforovta** [Kotlin-Polytech/KotlinAsFirst2018#12]
"например, номер 12 --  34- 5 -- 67 -**98** тоже следует считать легальным.
 Перевести номер в формат без скобок, пробелов и чёрточек (но с +), например,
 "+79211234567" или "1234567**89**" ### для приведённых примеров."

**Comment by gagarski** [comment]
Починено в 4a11d744e49f77c1e39d3dec5a74f334e08d5820.
Можете влить изменения из этого репозитория к себе, либо перенести их вручную.
