### ISSUE TITLE
Ошибка в тесте

### ISSUE THREAD

**Issue by lunakoly** [Kotlin-Polytech/KotlinAsFirst2018#2]
_lesson5.task1.RandomTests_ (_findSumOfTwo_)
Ошибка при проверке вывода.

**Ввод:**
"list" -> [
    1,
    45091,
    1,
    7738,
    28424,
    1,
    28158,
    44506,
    46285,
    26668,
    29617,
    1,
    0,
    2815,
    40699
]
"number" -> 1

**Вывод:** (0, 12)
**Ожидалось:** (11, 12)

Под индексом 12 стоит "0", под 0 и 11 стоят "1", поэтому эти ответы эквивалентны.

**Comment by ice-phoenix** [comment]
Спасибо за найденную ошибку, исправили
