### ISSUE TITLE
revert(Int.MAX_VALUE) в Уроке 3

### ISSUE THREAD

**Issue by DiscreetIntellectual** [Kotlin-Polytech/KotlinAsFirst2018#6]
Тестирующая система на Котоеде однажды выдала ошибку, когда моя программа в ответ на их случайный тест попыталась перевернуть число, равное Int.MAX_VALUE. Ошибка связана с тем, что функция возвращает Int, а перевернутое от 2147483647 не влезает в Int. Как поступить в этом случае? Не могла бы тестирующая система в Котоеде принимать Long как результат работы функции, вместо Int? Либо не генерировать настолько такие случайные тесты, на которые функция revert не может дать правильный ответ, так как возвращает только Int?

**Comment by ice-phoenix** [comment]
Если вы обратите внимание, то проблема у вас возникает не при тестировании 
функции revert, а при тестировании функции isPalindrome, которую вы решили 
- весьма смекалисто - через функцию revert. Однако оказывается, что данные 
функции работают и имеют смысл для разного диапазона входных данных.

Подумайте, как можно справиться с этой проблемой?
