### ISSUE TITLE
Ошибка в тестах printMultiplicationProcess

### ISSUE THREAD

**Issue by lunakoly** [Kotlin-Polytech/KotlinAsFirst2018#8]
Lesson 7 > **RandomTests** > *printMultiplicationProcess()*

Expected:
```
      33673
*     98690
-----------
          0
+   303057
+  202038
+ 269384
+303057
-----------
 -971778926
```

**-971778926** - это результат переполнения Int при перемножении. Должно было быть **3323188370**

**Comment by mglukhikh** [comment]
Я здесь предлагал бы во избежании двузначных толкований просто не генерировать тестовые примеры, которые дают результат больше максимального Int.

**Comment by mglukhikh** [comment]
Пофикшено в случайных тестах
